name: lucky-diff
services:
- dockerfile_path: dockerfiles/prod.Dockerfile
  github:
    branch: testing-do-deploy
    deploy_on_push: true
    repo: stephendolan/lucky_diff
  name: lucky-diff
  envs:
    - key: LUCKY_ENV
      scope: RUN_TIME
      value: production